version: '3'

services:

  app:
    build:
      context: .
      dockerfile: compose/app/Dockerfile
    container_name: therapy_center_app
    depends_on:
      postgres:
        condition: service_healthy
    env_file: .env
    volumes:
      - .:/app
    ports:
      - "8001:5000"
    command: /start_app.sh

  postgres:
    image: postgres:14.3
    container_name: postgres_therapy_center
    user: postgres
    volumes:
      - ${POSTGRES_DATA}:/var/lib/postgresql/data:Z
    env_file:
      - .env
    healthcheck:
      test: /usr/bin/pg_isready
      interval: 5s
      timeout: 10s
      retries: 120
    ports:
      - "5434:5432"
