"""Email user

Revision ID: 4606c463e8b6
Revises: 3814b26af97d
Create Date: 2026-05-29 16:00:03.213163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4606c463e8b6'
down_revision: Union[str, None] = '3814b26af97d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.String(length=254), nullable=False))
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.create_unique_constraint(None, 'user', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('user', 'email')
    # ### end Alembic commands ###
