"""Instructor model edited

Revision ID: 8678badb95e0
Revises: edd607ca2702
Create Date: 2024-10-11 20:13:12.076844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8678badb95e0'
down_revision: Union[str, None] = 'edd607ca2702'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instructor', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'instructor', 'user', ['user_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'instructor', type_='foreignkey')
    op.drop_column('instructor', 'user_id')
    # ### end Alembic commands ###
