"""Instructor model edited

Revision ID: 9a9c8ed1b90a
Revises: 8678badb95e0
Create Date: 2024-10-11 20:51:03.391392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a9c8ed1b90a'
down_revision: Union[str, None] = '8678badb95e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('instructor_username_key', 'instructor', type_='unique')
    op.drop_column('instructor', 'username')
    op.drop_column('instructor', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instructor', sa.Column('password', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.add_column('instructor', sa.Column('username', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.create_unique_constraint('instructor_username_key', 'instructor', ['username'])
    # ### end Alembic commands ###
