"""role name as str

Revision ID: ed431e0f682c
Revises: 6bb26d1986d3
Create Date: 2026-05-21 11:19:55.307000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed431e0f682c'
down_revision: Union[str, None] = '6bb26d1986d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('role', 'name',
               existing_type=sa.UUID(),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.drop_constraint(op.f('role_name_key'), 'role', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('role_name_key'), 'role', ['name'], postgresql_nulls_not_distinct=False)
    op.alter_column('role', 'name',
               existing_type=sa.String(length=100),
               type_=sa.UUID(),
               existing_nullable=False)
    # ### end Alembic commands ###
